Add dApp-to-dApp cases
wavesplatform/ride-examples pull request #47
Opened 2021-06-16 08:58 UTC by xrtm000

2021-06-23 14:38 UTC, DrBlast requested changes

2021-06-23 14:38 UTC, DrBlast commented on dApp-to-dApps/add-pool-liquidity/staker.ride
> +       [ IntegerEntry(i.caller.toString(), currentLiquidity + i.payments[0].amount) ]
i.originCaller

2021-06-23 14:38 UTC, DrBlast commented on dApp-to-dApps/swap/staker.ride
> +       let currentLiquidity = this.getInteger(i.caller.toString()).valueOrElse(0)
i.originCaller?

2021-06-23 18:25 UTC, xrtm000 commented on dApp-to-dApps/add-pool-liquidity/staker.ride
> +       [ IntegerEntry(i.caller.toString(), currentLiquidity + i.payments[0].amount) ]
Done

2021-06-23 18:25 UTC, xrtm000 commented on dApp-to-dApps/swap/staker.ride
> +       let currentLiquidity = this.getInteger(i.caller.toString()).valueOrElse(0)
Done

2021-07-06 16:47 UTC, msmolyakov approved these changes

2021-07-06 18:21 UTC, KardanovIR approved these changes

2021-07-06 18:21 UTC, merged